### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by larroy** [cyborgcnc/CYBORGCNC__RRVC3MOD#1]
Hi

Thanks for this great mod. What's the license? Can we use it?

Thank you!

**Comment by cyborgcnc** [comment]
GNU General Public License v3.0

In what capacity do you want to use it?  Can you please elaborate?

thanks,

Spiro

**Comment by larroy** [comment]
I was referred to this design from the Ratrig community discord. I would like to use it personally, at least at first. For commercial use I would let you know.

**Comment by cyborgcnc** [comment]
You can use it personally, but NOT for commercial use…

Thanks.

**Comment by larroy** [comment]
Thanks. The GPL would allow to use it commercially but bound to release any modifications with also GPL license though.
