### ISSUE TITLE
300mm lid remix missing bottom bar STLs

### ISSUE THREAD

**Issue by ChewyJetpack** [cyborgcnc/CYBORGCNC__RRVC3MOD#3]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/11411735/136043346-1dbe1236-6074-488d-9d71-2c81f678f895.png">

See above list of STLs from the zip file. 

The side bars are there; 'Btm-Bar-SIDES.HALF 4no.stl', but no front/back bars included.

**Comment by ChewyJetpack** [comment]
I don't have Facebook so I can't get in touch with Phil there, but it would be massively appreciated if he could update the zip file - I've printed all the other parts.

**Comment by ChewyJetpack** [comment]
[Lid_Bottom_Center_v2_300x300.stl.zip](https://github.com/cyborgcnc/CYBORGCNC__RRVC3MOD/files/7296348/Lid_Bottom_Center_v2_300x300.stl.zip)
Here is the missing stl provided by @RPK3D on the RR discord.

**Comment by cyborgcnc** [comment]
Thank you ..will post later…
