### ISSUE TITLE
Contrib: 300mm version of Carbon Filter fan duct

### ISSUE THREAD

**Issue by jbjhjm** [cyborgcnc/CYBORGCNC__RRVC3MOD#7]
I rebuilt the Carbon Filter fan duct to fit for a 300mm V-Core 3. 
No time to open a PR but I thought you may want to add it.
Zip contains step and stl.

[Activated-Carbon-Filter.zip](https://github.com/cyborgcnc/CYBORGCNC__RRVC3MOD/files/7618440/Activated-Carbon-Filter.zip)

**Comment by cyborgcnc** [comment]
Thank you Jannik!!

I will post this to the Github repository, and make sure I mention you in
the credits!

GOOD WORK!

Spiro
